"""empty message

Revision ID: 04ff0b9538d6
Revises: ffc45501c617
Create Date: 2020-08-22 19:24:41.345096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04ff0b9538d6'
down_revision = 'ffc45501c617'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'Artist', ['image_link'])
    op.create_foreign_key(None, 'Show', 'Artist', ['image_link'], ['image_link'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Show', type_='foreignkey')
    op.drop_constraint(None, 'Artist', type_='unique')
    # ### end Alembic commands ###
