"""initial migration

Revision ID: 8418db82c4b4
Revises: 
Create Date: 2020-08-15 15:43:06.595465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8418db82c4b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Artist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=120), nullable=True),
    sa.Column('genres', sa.String(length=120), nullable=True),
    sa.Column('image_link', sa.String(length=500), nullable=True),
    sa.Column('facebook_link', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Venue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.Column('address', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=120), nullable=True),
    sa.Column('image_link', sa.String(length=500), nullable=True),
    sa.Column('facebook_link', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('ex_table2')
    op.drop_table('ex_table1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ex_table1',
    sa.Column('dog1', sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.create_table('ex_table2',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cat_type', sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.drop_table('Venue')
    op.drop_table('Artist')
    # ### end Alembic commands ###
